#!/bin/sh
#
# Cobalt
#
# chkconfig: 2345 18 09
# description: Cobalt resource manager/scheduler
#

prefix=/usr
exec_prefix=/usr/bin
CONFIGPATH=/etc
CONFIGFILE="${CONFIGPATH}/cobalt.conf"
DAEMONDIR=/usr/sbin
PIDPATH=/var/run/

# Configure DB2 environment
# . /discovery/db.src

umask 077

# ANL Local:
# MPIRUN_VERBOSE=1
# export MPIRUN_VERBOSE
# LD_LIBRARY_PATH=/bgsys/drivers/ppcfloor/lib64:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH

# Starts the component specified as the first argument.
# Optional second argument used for extra arguments to 
# pass to the component.
start_component () {
    component=$1
    if [ -n $2 ] ; then
	component_args=$2
    else
	component_args=''
    fi
    pid=`pgrep ${component}.py`
    echo -n "Starting ${component}: "
    if [ -z "$pid" ]
    then
        (
         date=`/bin/date`
         echo "--- $date: START ${component} ---" >>/var/log/${component}.out
         nohup "${DAEMONDIR}/${component}.py" $component_args --config-files "${CONFIGFILE}" >>/var/log/${component}.out 2>&1 &
        )
        echo "done"
        return 0
    else
        echo "failed -- $component already running (pid $pid)"
        return 1
    fi
}

# Stops the component specified as the first argument.
stop_component () {
    component=$1
#   if [ -f "${PIDPATH}/${component}.pid" ] ; then
       echo -n "Stopping ${component}: "
#       kill -INT `cat ${PIDPATH}/${component}.pid`
	pkill -f ${DAEMONDIR}/${component}.py
        echo "done"
#       rm -f "${PIDPATH}/${component}.pid"
#   else
#       echo "${component} not running"
#   fi
    return 0
}


case "$1" in
  start)
    for component in slp cqm bgsched bgforker bgsystem cdbwriter scriptm; do
	start_component $component
    done
    touch /var/lock/subsys/cobalt
    ;;
  start-debug)
    for component in slp brooklyn cqm bgsched bgforker bgsystem cdbwriter scriptm; do
	start_component $component
    done
    touch /var/lock/subsys/cobalt
    ;;
  stop)
    for component in slp cqm bgsched bgforker bgsystem cdbwriter scriptm; do
	stop_component $component
    done
    rm -f /var/lock/subsys/cobalt
    ;;
  stop-debug) 
    for component in slp brooklyn cqm bgsched bgforker bgsystem cdbwriter scriptm; do
	stop_component $component
    done
    rm -f /var/lock/subsys/cobalt
    ;;
  restart)
    if [ $# -gt 1 ] ; then  #specific components to be restarted
	shift
	for component in $@; do 
	    case "$component" in 
	      cqm|bgsched)
		stop_component $component
		start_component $component
		;;
	      slp|bgpm)
		echo "${component} cannot be restarted with jobs running"
		;;
	    esac
	done
    else  #restart all components
	$0 stop
	$0 start
    fi
    ;;
  force-reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1
esac

exit 0
