.TH "bgqm" 8
.SH NAME
bgqm \- Blue Gene/L Process Manager
.SH SYNOPSIS
.B bgqm 
.I [-d] [--notbgl] [-C <configfile>] [-D=<pidfile>]
.SH "DESCRIPTION"
.PP
.B bgqm 
Blue Gene/L Process Manager
.SH "OPTIONS"
.TP
.B \-d
Turn on communication debugging.
.TP
.B \-\-notbgl
Debugging mode, where mpirun is not used to launch executable. The executable is run directly.
.TP
.B \-C <configfile>
Specify path to cobalt.conf.
.TP
.B \-D=<pidfile>
Daemonize, and write pid to pidfile.
.SH "CONFIGURATION FILE PARAMETERS"
.TP
.B bridge_config=/path/to/bridge.config
Set bridge config file for user jobs.
.TP
.B db2_instance=dbname
Set the database name in DB/2 for user jobs
.TP
.B db2_connect=/path/to/db2_connect
Path to the db2connect executable
.TP
.B db2_properties=/path/to/db.properties
Path to the db.properties file.
.TP
.B mmcs_server_id=ipaddress
IP address of the MMCS server
.TP
.B mpirun=/path/to/mpirun
Set path to the mpirun executable.
.SH "SEE ALSO"
.BR pmstat(1)
