.TH "cqadm" 8
.SH "NAME"
cqadm \- queue manager administration tool
.SH "SYNOPSIS"
.B cqadm [-d] [--hold] [--release] [--run=<location>] [--kill] [--delete] [--queue=newqueue] <jobid> <jobid>

.B cqadm [-d] [--addq] [--delq] [--getq] [--setq 'prop:value prop:value'] <queue> <queue>

.SH "DESCRIPTION"
Administrative interface for queue manager. Allows one to hold, run, kill, and set the queue for jobs in the queue manager. Can also add/del queues and set queue properties.

.SH "OPTIONS"
.TP
.B \-d
Enable communication debugging
.TP
.B \-\-hold jobid
Set job state to hold, preventing execution
.TP
.B \-\-release jobid
Set job state to ready, allowing execution
.TP
.B \-\-run=<location> jobid
Run the job immediately on the specified location
.TP
.B \-\-kill jobid
Kill job(s) using normal mechanism
.TP
.B \-\-delete jobid
Kill job(s) using forceable deletion. Job state will be deleted. This
may leave processes dangling on computation resources. 
.TP
.B \-\-queue=<queue>
Change job queue to specified one
.TP
.B \-\-addq queue
Add specified queue(s) to queue manager
.TP
.B \-\-delq queue
Delete specified queue(s) from queue manager
.TP
.B \-\-getq queue
List queue(s) in queue manager
.TP
.B \-\-setq 'prop:value prop:value' queue
Set properties for one or more queues. The prop:value pairs are separated by whitespace. 
.IP 
Example:
.IP
cqadm --setq 'maxtime=01:00:00 users=mike:john:george' someq
.IP
Properties:
.RS
.TP
.B maxtime=mm
The maximum walltime (in minutes) allowed for jobs submitted to the queue.
.TP
.B users
List of users allowed to submit to the queue. An '*' means any user can submit to the queue
.TP
.B state=running|stopped|draining
Flag determining state of queue. If the queue is 'stopped', jobs can be submitted to the queue, but no jobs will be run by the scheduler. If the queue is 'draining', no new jobs will be allowed to be added to the queue, but jobs existing in the queue will be run.

.RE
.SH "SEE ALSO"
.BR cqm(8)
.SH "BUGS"
