.TH "cqdel" 1
.SH NAME
cqdel \- Delete job from the queue manager
.SH SYNOPSIS
.B cqdel
.I [--version] [-d] [jobid1] [jobid2]
.SH DESCRIPTION
.PP
.B cqdel
Delete a job from the queue. 
.SH OPTIONS
.TP
.B \-\-version
Print out version string
.TP
.B \-d
Run in debugging mode.
.TP
.SH "SEE ALSO"
.BR cqstat(1),
.BR cqsub(1),
.BR cqm(1)
.SH BUGS
None are currently known.