.TH "cqhist" 1
.SH NAME
cqhist \- show info for completed jobs
.SH SYNOPSIS
.B cqhist
.I [-a]
.SH DESCRIPTION
.PP
This program queries the queue manager for completed jobs stats.
.SH OPTIONS
.TP
.B \-a
Show expanded information for each job
.TP
.B \-\-version
Print out version string
.SH "SEE ALSO"
.BR cqdel(1),
.BR cqsub(1),
.BR cqm(8)
.SH BUGS
None are currently known.
