.TH "nodelist" 1
.SH "NAME"

nodelist

.SH "SYNOPSIS"
.B nodelist [options] 

.SH "DESCRIPTION"
.TP
List resources on the cluster system.

.SH "OPTIONS"

.TP
.B \-d \-\-debug
Turn on communication debugging.
.TP
.B \-h \-\-help
Displays the usage and a brief descriptions of the options
.TP
.B \-\-version
Displays client revision and Cobalt version

.SH "SEE ALSO"
.BR nodeadm (8)
.SH "BUGS"
