.TH "partadm" 8
.SH "NAME"
partadm \- partition administration tool
.SH "SYNOPSIS"
.B partadm [-a|-d] [-s size] part1 part2
.TP
.B partadm [--activate|--deactivate] part1 part2
.TP
.B partadm [--enable|--disable] part1 part2
.TP
.B partadm [--deps=dep1:dep2] part1 part2
.TP
.B partadm --free part1 part2
.SH "DESCRIPTION"
.TP
.B \-a
Add new partitions (of specified size) into the scheduler
.TP
.B \-d 
Delete partitions from the scheduler
.TP
.B \-\-activate
Set the partition as functional.
.TP
.B \-\-deactivate
Se the partition as non-functional. (Jobs will not be run on
non-functional partitions, or any overlapping partitions)
.TP
.B \-\-enable
Allow partition(s) to have jobs scheduled on them
.TP
.B \-\-disable
Do not run jobs on this partition(s). (Jobs can run on larger or
smaller overlapping partitions)
.TP
.B \-\-deps
Set partition(s) dependencies
.TP
.B \-\-free
Forceably free partition (set state to idle)
.TP
.B \-\-dump
Dump partition state
.TP
.B \-\-load <filename>
Load partition state from file. Note that this is not exclusive;
existing partitions will continue to exist.
.SH "SEE ALSO"
.BR partlist(1)
.SH "BUGS"
