.TH "scriptm" 8
.SH NAME
scriptm \- Cobalt Script Manager
.SH SYNOPSIS
.B scriptm
.I [-d] [--config-files <configfile1:configfile2>] [-D=<pidfile>]
.SH "DESCRIPTION"
.PP
.B scriptm
Cobalt Script Manager.  This component handles execution of jobs that submitted as type script.
.SH "OPTIONS"
.TP
.B \-d
Turn on communication debugging.
.TP
.B \-\-config-files <configfile1:configfile2>
Specify path to cobalt.conf.
.TP
.B \-D=<pidfile>
Daemonize, and write pid to pidfile.
.SH "CONFIGURATION FILE PARAMETERS"
.TP
none
