.TH "setres" 8
.SH "NAME"
setres \- Create a new cobalt scheduler reservation
.SH "SYNOPSIS"
.B setres [--version] [-a] [-x] [-m] [-p partition] [-s starttime] [-d duration] [-u user] [-n name] [partion1 partion2 ... partitionN]
.SH "DESCRIPTION"
.TP
This program creates new scheduler reservations.
.TP
.B \-m
Modify an existing reservation, specified with -n.
.TP
.B \-p
Set use partition (or quoted "*" as a wildcard). Now optional
.TP
.B \-n
Set reservation name
.TP
.B \-s
Set start time (in format YYYY_MM_DD-HH:MM)
.TP
.B \-d
Set duration (in minutes or DD:HH:MM)
.TP
.B \-u
Set user for reservation
.TP
.B \-a 
Enable auto dependancy generation for listed partition(s)
.TP
.B \-x 
Reserve the partition for exclusive access (also reserves all client and parent partitions)
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR showres(1)
.BR releaseres(8)
.SH "BUGS"
