.TH "showres" 1
.SH "NAME"
showres \- show all reservations
.SH "SYNOPSIS"
.B showres [--version] [-d] [-l]
.SH "DESCRIPTION"
.TP
This program lists all reservations.
.SH OPTIONS
.TP
.B \-d
Turn on communication debugging
.TP
.B \-l
Display shortened reservation listing
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR setres(8)
.BR releaseres(8)
.SH "BUGS"
