.TH "slpstat" 8
.SH "NAME"
slpstat \- Queries the slp daemon for component location information
.SH "SYNOPSIS"
.B slpstat [--version]
.SH "DESCRIPTION"
.TP
This program queries slp for component locations.
.TP
.B \-d
Show protocol debugging messages
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR slp(8)
.SH "BUGS"
