.TH "userres" 1
.SH "NAME"
userres \- Delete non cyclic cobalt reservation(s) or reschedule to next cycle for cyclic reservations.
.SH "SYNOPSIS"
.B userres [ options ] name
.SH "DESCRIPTION"
.TP
This program deletes scheduler reservation(s) or schedule to next cycle for cyclic reservation(s).
.SH OPTIONS
.TP
.B \-d \-\-debug
Turn debug on
.TP
.B \-h \-\-help
Displays command help
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR showres(1)
.BR releaseres (8)
.BR setres(8)
.SH "BUGS"
