.TH "qalter" 1
.SH "NAME"
qalter \- change properties of jobs already submitted to the queue manager
.SH "SYNOPSIS"
.B qalter 
.I [--version] [-d] [-A project] [-t time] [-n number of nodes] [--mode mode] [--procccount process count] [--run_users user1:user2:...] <jobid1> <jobid2>
.SH "DESCRIPTION"
.PP
.B qalter
changes properties of jobs already submitted to the queue manager
.SH "OPTIONS"
.TP
.B \-d
Turn on communication debugging.
.TP
.B \-\-version
Print out version string
.TP
.B \-\-mode "mode"
Either co (for coprocessor mode) or vn (for virtual node mode) or script (for script jobs)
.TP
.B \-n "node count"
Specifies the node count for a job
.TP
.B \-\-proccount "process count"
Specify the number of processes to start
.TP
.B \-A "project"
Associate the job with the allocation for project project. This is
used to properly account for machine usage. 
.TP
.B \-t "wall clock time" 
Specify the runtime for a job. The time specified is the full amount in minutes
allotted to the job for execution. If the job runs over this limit, it
will be killed. If colon-delimited time is specified, the format is HH:MM:SS.

Also note that relative time is allowed.  A time argument with a '+' at the
beginning will add the argument amount to the current walltime, while an argument
with a '-' at the beginning will subtract the argument amount from the current
walltime.
.TP
.B \-M "email address"
Send an email notification at the start and stop of the job to the
specified email address.
.TP
.B \-e "stderr file path"
Send job stderr to file specified.
.TP
.B \-o "stdout file path"
Send job stdout to file specified.
.TP
.B \-\-run_users <user1>:<user2>
Sets a colon-separated list of users for the job being submitted.  All users
in this list will be able to execute cobalt commands to control the job. The 
submitting user is always able to run commands on a submitted job.
.SH "SEE ALSO"
.BR qsub(1),
.BR qstat(1)
.SH "BUGS"
