.TH "qstat" 1
.SH NAME
qstat \- query the queue manager for jobs
.SH SYNOPSIS
.B qstat
.I [--version] [-d] [-f] [-l] <jobid> <jobid>
.TP
.B qstat
.I [-d] -q <queue> <queue>
.SH DESCRIPTION
.PP
.B qstat
query the queue manager for all queued and active jobs. 
.SH OPTIONS
.TP
.B \-d
Turn on communication debugging
.TP
.B \-f
Show more verbose information. 
.TP
.B \-l
Show job info in vertical format. Use with '-f' to get all job info.
.TP
.B \-\-header <header fields>
Specify custom header for qstat display with a colon-separated list. (See qstat -lf for the possible fields.) The custom header may also be specified setting QSTAT_HEADER in the environment or a cqstat_header entry under [cqm] in /etc/cobalt.conf. The header is taken from /etc/cobalt.conf first, then $QSTAT_HEADER, and finally qstat --header.
.IP
.B Example:
.RS
.TP
qstat --header JobId:State:RunTime
.RE
.TP
.B \-Q
Show queues and properties.
.IP
.B Properties:
.RS
.TP
.B MaxTime
The maximum walltime (in minutes) allowed for jobs submitted to the queue.
.TP
.B MinTime
The minimum walltime (in minutes) allowed for jobs submitted to the queue.
.TP
.B MaxQueued
The maximum number of jobs a user is allowed to have in the queue, whether running or queued.
.TP
.B Users
List of users allowed to submit to the queue. "None" means any user can submit to the queue.
.TP
.B State=running|stopped|draining|dead
Flag determining state of queue. If the queue is 'stopped', jobs can be submitted to the queue, but no jobs will be run by the scheduler. If the queue is 'draining', no new jobs will be allowed to be added to the queue, but jobs existing in the queue will be run. If the queue is 'dead', no new jobs will be added and no existing jobs will be run.
.TP
.B MaxRunning
The maximum number of jobs a user is allowed to have running in the queue.
.TP
.B MaxUsernodes
The maximum number of nodes a user is allowed to have allocated with running jobs in the queue.
.TP
.B TotalNodes
The maximum number of nodes any jobs in the queue are allowed to have allocated with running jobs.
.TP
.B Priority
The priority of the queue.  Higher numbers have higher priority.
.RE
.TP
.B \-\-version
Displays client revision and Cobalt version
.PP
.SH "ENIRONMENT VARIABLES"
The following environment variables affect qstat:
.TP
.B QSTAT_HEADER
Specifies custom header for job queries (See --header).
.SH "SEE ALSO"
.BR qdel(1),
.BR qsub(1),
.BR cqm(1)
.SH BUGS
None are currently known.