.TH "qdel" 1
.SH NAME
qdel \- Delete job from the queue manager
.SH SYNOPSIS
.B qdel
.I [options]  jobid1 [jobid2 ... jobidN]
.SH DESCRIPTION
.PP
.B qdel
Delete a job from the queue. 
.SH OPTIONS
.TP
.B \-d \--debug
Turn on communication debugging
.TP
.B \-h \-\-help
Displays the usage and a brief descriptions of the options
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR qstat (1),
.BR qsub (1),
.BR cqm (1)
.SH BUGS
None are currently known.
