.TH "qdel" 1
.SH NAME
qdel \- Delete job from the queue manager
.SH SYNOPSIS
.B qdel
.I [--version] [-d] [jobid1] [jobid2]
.SH DESCRIPTION
.PP
.B qdel
Delete a job from the queue. 
.SH OPTIONS
.TP
.B \-\-version
Print out version string
.TP
.B \-d
Run in debugging mode.
.SH "SEE ALSO"
.BR qstat(1),
.BR qsub(1),
.BR cqm(1)
.SH BUGS
None are currently known.