.TH "qhold" 1
.SH NAME
qhold \- Place a "queued" job into a "user hold" state, which prevents Cobalt from attempting to start it.
.SH SYNOPSIS
.B qhold
.I [--version] [jobid1] [jobid2]
.SH DESCRIPTION
.PP
.B qhold
Place a hold on a job. 
.SH OPTIONS
.TP
.B \-\-version
Print out version string
.SH "SEE ALSO"
.BR qrls(1)
.SH BUGS
None are currently known.