.TH "qrls" 1
.SH NAME
qrls \- Release a previously applied "user hold" from a job.
.SH SYNOPSIS
.B qrls
.I [--version] [jobid1] [jobid2]
.SH DESCRIPTION
.PP
.B qrls
Remove a hold from a job. 
.SH OPTIONS
.TP
.B \-\-version
Print out version string
.SH "SEE ALSO"
.BR qhold(1)
.SH BUGS
None are currently known.