.TH "qselect" 1
.SH "NAME"
qselect \- shows the jobids of all of the pending jobs matching the selection criteria
.SH "SYNOPSIS"
.B qselect 
.I [options]
.SH "DESCRIPTION"
.PP
.B qselect
shows the jobids of all of the pending jobs matching the selection criteria
.SH "OPTIONS"
.TP
.B \-d \--debug
Turn on communication debugging
.TP
.B \-\-help
Displays the usage and a brief descriptions of the options
.TP
.B \-\-version
Displays client revision and Cobalt version
.TP
.B \-A \-\-project "project"
Specifies the project with which the job is associated.
.TP
.B \-h \-\-held "state"
Specifies the held state of the job.
.TP
.B \-\-mode "mode"
Specifies the job mode.
.TP
.B \-n \-\-nodecount "node count"
Specifies the node count for a job.
.TP
.B \-q \-\-queue "queue"
Specifies the queue in which the job resides.
.TP
.B \-t \-\-time "wall clock time" 
.TP
.B \-v \-\-verbose
not used
Specifies the runtime for a job. The time specified is the full amount in minutes
allotted to the job for execution. If the job runs over this limit, it
will be killed. If colon-delimited time is specified, the format is HH:MM:SS.
.SH "SEE ALSO"
.BR qsub (1),
.BR qstat (1)
.SH "BUGS"
