.TH "qselect" 1
.SH "NAME"
qselect \- shows the jobids of all of the pending jobs matching the selection criteria
.SH "SYNOPSIS"
.B qselect 
.I [--version] [-d] [-A project] [-t time] [-n number of nodes] [--mode mode] [-q queue] [-h state] <jobid1> <jobid2>
.SH "DESCRIPTION"
.PP
.B qselect
shows the jobids of all of the pending jobs matching the selection criteria
.SH "OPTIONS"
.TP
.B \-d
Turn on communication debugging.
.TP
.B \-\-version
Print out version string.
.TP
.B \-\-mode "mode"
Specifies the job mode.
.TP
.B \-n "node count"
Specifies the node count for a job.
.TP
.B \-A "project"
Specifies the project with which the job is associated.
.TP
.B \-t "wall clock time" 
Specifies the runtime for a job. The time specified is the full amount in minutes
allotted to the job for execution. If the job runs over this limit, it
will be killed. If colon-delimited time is specified, the format is HH:MM:SS.
.TP
.B \-q "queue"
Specifies the queue in which the job resides.
.TP
.B \-h "state"
Specifies the state of the job.
.SH "SEE ALSO"
.BR qsub(1),
.BR qstat(1)
.SH "BUGS"
