.SH "NAME"
.TH "qsub" 1
qsub \- submit jobs to the queue manager for execution
.SH "SYNOPSIS"
.B qsub 
.I [<options>] <executable> [<executable options>]
.SH "DESCRIPTION"
.PP
.B qsub
submits a job to the queue manager for execution. 

   jobid expansion:
      If \\$jobid is specified in any jobid expansion option then it will be converted to the actual jobid.

      Example: qsub ... --env myenv=\\$jobid_myval ... 

               if the jobid is 123 then myenv will be set to '123_myval'

      jobid expansion options: --env, --jobname, -o, -e, -O, --debuglog

.SH "OPTIONS"
.TP
.B \-d \-\-debug
Turn on communication debugging
.TP
.B \-\-help
Displays the usage and a brief descriptions of the options
.TP
.B \-\-version
Displays client revision and Cobalt version
.TP
.B \-A \-\-project [project]
Associate the job with the allocation for project project. This is
used to properly account for machine usage. 
.TP
.B \-\-attrs [<attr1=val1>:<attr2=val2>:...]
Set a list of attributes for a job that must be fulfilled for a job to run.  
For instance, --attrs location=[blocklocation] will force a job to run on a 
specific block.
.TP
.B \-\-cwd [directory]
Tell the job to use the specified directory as the default current working directory
while running the job.
.TP
.B \-\-debuglog [path to file] - (jobid expansion)
Send debugging information from cobalt to file specified.
.TP
.B \-\-dependencies [<jobid1>:<jobid2>:...]
Set the dependencies for the job being submitted.  This job won't run until 
all jobs in the dependency list have finished and exited with a status of 0.
.TP
.B \-\-disable_preboot
If --mode script is specified, this will cause Cobalt to run the job script without
booting the block first.  By default the script is executed after the requested block is booted.
.TP
.B \-e \-\-error [path to file] - (jobid expansion)
Send job stderr to file specified.
.TP
.B \-\-env [<var1=value1>:<var=value2>] - (jobid expansion)
Set environment variables that will be passed into the job's environment at 
If the the characters ":" and "=" are within the value, right hand side (rhs) of a environment variable assignment,
then need to quote the entire string and precede any ":" and "=" characters that are in the rhs with "\\". 
runtime. 

e.g. qsub ... --env "A=B:C=x\\=1\\:y\\=2\\:z\\=3:D=ABC" ...

A would equal B

C would equal x=1:y=2:z=3

D would equal ABC
.TP
.B \-\-jobname [job name] - (jobid expansion)
Sets Jobname. If this option is not provided then Jobname will be set to whatever -o option specified.'
.TP
.B \-\-geometry <geometry_spec>
Sets the geometry of the block that the jobs should run on.  This is in
the form of AxBxCxDxE.  This must be the geometry of the compute block.
This may not be a fraction of a block.
.TP
.B \-h \-\-held
Submit job and immediately place it in the user hold state
.TP
.B \-i \-\-inputfile [path to file]
Send file to job's stdin.
.TP
.B \-I (NOT IMPLEMENTED)
Run an interactive command. During job execution, the current tty will
be connected with the running job. (Not available on Blue Gene systems.)
.TP 
.B \-M \-\-notify [email address]
Send an email notification at the start and stop of the job to the
specified email address.
.TP
.B \-n \-\-nodecount [nodecount]
Specifies the node count for a job
.TP
.B \-o \-\-output [path to file] - (jobid expansion)
Send job stdout to file specified.
.TP
.B \-O \-\-outputprefix [output prefix] - (jobid expansion)
Use the specified prefix for both .output, .error and debuglog files. This will only take effect if \-o or \-e or \-\-debuglog not supplied. 
.TP
.B \-\-proccount [process count]
Specify the number of processes to start.
.TP
.B \-q \-\-queue [queue] 
Submit the job to the specified queue.
.TP
.B \-\-run_users \-\-user_list [<user1>:<user2>:...]
Sets a colon-separated list of users for the job being submitted.  All users
in this list will be able to execute cobalt commands to control the job. The 
submitting user is always able to run commands on a submitted job.
.TP
.B \-\-run_project
Appends the list of users in a project to the list of users authorized to run
commands on the submitted job. 
.TP
.B \-u \-\-umask'
set umask: octal number default(022)
.TP
.B \-t \-\-time [wallclock time] 
Specify the runtime for a job. If the job runs over this limit, it will be 
killed. The time may be specified as eitehr an integer number of minutes or a 
colon-delimited value of the format: HH:MM:SS.
.TP


.SH "BLUEGENE OPTIONS"
.TP 
The following commands are only valid on IBM BlueGene architecture platforms.
.TP
.B \-\-kernel [kernel profile]
Run the job with the specified kernel profile.
.TP
.B \-K \-\-kerneloptions [kernel options]
Run the job with the specified kernel options (equivalent to 
.Impirun -kernel_options 
on Blue Gene/L).
.TP
.B \-\-mode [mode]
This is a platform-dependent setting that controls the execution mode of the 
submitted job and the division of cores and memory on the compute nodes.  
Valid values are dependent on the specific BlueGene platform:
.TP
BG/L: Valid values are "co" (coprocessor),"vn" (virtual node) and "script".  
      The default is co.
.TP
BG/P: Valid values are "smp", "dual", "vn" and "script".   "smp", "dual" and 
      "vn" correspond to the modes within mpirun. The default is "smp" 
.TP
BG/Q: Valid values are "c1","c2","c4","c8","c16","c32","c64", and "script".  
      The c(n) modes correspond to the "ranks-per-node" flag of runjob and 
      governs the MPI ranks started per node on the compute nodes.  Node memory
      is divided evenly between all processes.  n/64 threads will be available 
      to each MPI process as well. If this option is not set the default is "c1"
.TP
On all platforms, the "script" mode causes the job to be routed through the 
script-forker, and will allow the execution of script jobs
allows the user to  

.SH "NOTE"
The only thing printed to STDOUT is the jobid, any other error or informational messages are printed to STDERR.
.SH "SEE ALSO"
.BR qstat(1),
.BR qdel(1),
.BR qhold(1),
.BR qrls(1),
.BR qalter(1),
.BR qmove(1),
.BR cqm(1),
.BR cqwait(1)
.SH "BUGS"
