.TH "cam" 8
.SH NAME
cam \- handle allocations and users for projects 
.SH SYNOPSIS
.B cam
.I 
.SH DESCRIPTION
.PP
.B The Allocation Manager handles projects, users in these projects, and the
allocations each of these projects has. It is an sss component which registers
itself with the service directory.
.SH "SEE ALSO"
.BR showp(1),
.BR setp(1),
.BR camadmin(1)
.SH BUGS
