.TH "cqhist" 1
.SH NAME
cqhist \- show info for completed jobs
.SH SYNOPSIS
.B cqstat
.I [-f] [-d days]
.SH DESCRIPTION
.PP
This program displays stats for completed jobs.
.SH OPTIONS
.TP
.B \-f
Show expanded information for each job
.TP
.B \-d days
Show jobs completed for past number of days. Defaults to 1 day.
.TP
.B \-\-version
Print out version string
.SH "SEE ALSO"
.BR cqdel(1),
.BR cqsub(1),
.BR cqm(1)
.SH BUGS
None are currently known.