.TH "partlist" 1
.SH "NAME"
partlist \-	List online partitions
.SH "SYNOPSIS"
.B partlist [--version]
.SH "DESCRIPTION"
.TP
This program lists all partitions that have been marked as functional. 
.PP
Partitions with 
.B idle 
state are free to run jobs. Partitions with 
.B busy 
state are running jobs. Partitions with 
.B blocked 
state are not able to run jobs because one or more of their parent or child partitions are running jobs.
.SH OPTIONS
.TP
.B \-\-version
Displays client revision and Cobalt version
.SH "SEE ALSO"
.BR partadm(8)
.SH "BUGS"
