.TH "releaseres" 8
.SH "NAME"
releaseres \- Delete cobalt scheduler reservation(s)
.SH "SYNOPSIS"
.B releaseres [-p partition] name
.SH "DESCRIPTION"
.TP
This program deletes scheduler reservation(s)
.TP
.B \-p
.I set partition name (or quoted "*" as a wildcard)
.SH "SEE ALSO"
.BR showres(1)
.BR setres(8)
.SH "BUGS"
