/*Autogenerated from python*/
// Copyright 2017 UChicago Argonne, LLC. All rights reserved.
// Licensed under a modified BSD 3-clause license. See LICENSE for details.
%module pybgsched

%{
#include <bgsched/ComputeHardware.h>
%}
%include "/bgsys/drivers/ppcfloor/hlcs/include/bgsched/ComputeHardware.h"

