/*Autogenerated from python*/
%{
#include <bgsched/bgsched.h>
%}

%immutable bgsched::version::driver;

%exception bgsched::init {
    try{
        $action
    } catch(bgsched::InitializationException &e) {
        PyErr_SetString(PyExc_IOError, const_cast<char *>(e.what()));
        return NULL;
    }
}



%include "/bgsys/drivers/ppcfloor/hlcs/include/bgsched/bgsched.h"


