#!/usr/bin/env python

import glob
import os.path

def gen_file_list(dir):

    files = glob.glob('/bgsys/drivers/ppcfloor/hlcs/include/%s/*.h'% dir)
    files = [os.path.basename(file) for file in files]
    files = [os.path.join(dir, file) for file in files]

    return files

def write_i_file(include_file):
    base_filename = os.path.basename(include_file)
    base_filename = base_filename.split(".")[0]
    target_file = '/bgsys/drivers/ppcfloor/hlcs/include/%s' % include_file
    f = open("%s.i" % base_filename , 'w+')
    f.write("/*Autogenerated from python*/\n")
    f.write('%%{\n#include <%s>\n%%}\n' % include_file)
    f.write('%%include "%s"\n' % target_file)
    f.close()
    return

if __name__ == '__main__':

    include_files = []
    include_files.extend(gen_file_list("bgsched"))
    #include_files.extend(gen_file_list("bgsched/allocator"))
    include_files.extend(gen_file_list("bgsched/core"))
    #include_files.extend(gen_file_list("bgsched/realtime"))
    #include_files.extend(gen_file_list("bgsched/runjob"))
   
    print "%module libbgsched" 
    
    for file in include_files:
	    write_i_file(file)
	    base_filename = os.path.basename(file)
	    base_filename = base_filename.split(".")[0]

	    print "%%include \"%s.i\"" % base_filename 
