/*Autogenerated from python*/
%include <boost_shared_ptr.i>

%shared_ptr(bgsched::Hardware)
%shared_ptr(bgsched::Midplane)
%shared_ptr(bgsched::Cable)
%shared_ptr(bgsched::Switch)
%shared_ptr(bgsched::NodeBoard)
%shared_ptr(bgsched::Node)
%shared_ptr(bgsched::IOLink)

%{
#include <bgsched/Hardware.h>
%}
%include "/bgsys/drivers/ppcfloor/hlcs/include/bgsched/Hardware.h"
