#! /bin/sh

echo "Running $0"

. $GLOBUS_LOCATION/libexec/globus-sh-tools.sh

GPATH=$GPT_LOCATION

if [ "$GPATH" = "" ]; then
    GPATH=$GLOBUS_LOCATION
fi

if [ "$GPATH" = "" ]; then
    echo "GPT_LOCATION or GLOBUS_LOCATION needs to be set before running this script."
fi

$GLOBUS_SH_PERL -I${GPATH}/lib/perl -I${GLOBUS_LOCATION}/lib/perl \
    ${GLOBUS_LOCATION}/setup/globus/setup-gram-manager.pl \
        -m "Cobalt" \
        -p "globus_wsrf_gram_service_java_setup_cobalt" \
        "$@"
