# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = $(GLOBUS_LOCATION)
exec_prefix = $(GLOBUS_LOCATION)

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/globus_gram_job_manager_setup_cobalt
pkglibdir = $(libdir)/globus_gram_job_manager_setup_cobalt
pkgincludedir = $(includedir)/globus_gram_job_manager_setup_cobalt

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = @host_alias@
host_triplet = @host@
AR = 
ARFLAGS = 
AS = @AS@
CC = 
CFLAGS = -g   -Wall
CPP = 
CPPFLAGS = 
CROSS = 
CXX = 
CXXCPP = 
CXXFLAGS = -g  
DIRT_BRANCH_ID = 99999
DIRT_TIMESTAMP = 1171837259
DLLTOOL = @DLLTOOL@
DOT = 
DOXYFILE = Doxyfile
DOXYGEN = 
EXEEXT = 
F77 = 
F77FLAGS = 
F90 = 
F90FLAGS = 
FILELIST_FILE = /home/copej/downloads/sge/globus_gram_job_manager_setup_cobalt-1.1/pkgdata/master.filelist
GLOBUS_FLAVOR_NAME = noflavor
GPT_CFLAGS = 
GPT_CONFIG_CFLAGS = 
GPT_CONFIG_INCLUDES = 
GPT_CONFIG_LIBS = 
GPT_CONFIG_PKG_LIBS = 
GPT_EXTERNAL_INCLUDES = 
GPT_EXTERNAL_LIBS = 
GPT_INCLUDES = -I/home/copej/tmp/ctss/globus-wsrf-4.0.1-r3/include/noflavor 
GPT_IS_2 = yes
GPT_LDFLAGS =  -L/home/copej/tmp/ctss/globus-wsrf-4.0.1-r3/lib 
GPT_LIBS =  
GPT_LIB_LINKS =  
GPT_LINKTYPE = shared
GPT_LOCATION = /home/copej/tmp/ctss/globus-wsrf-4.0.1-r3
GPT_MAJOR_VERSION = 1
GPT_MINOR_VERSION = 1
GPT_PGM_LINKS =  
GPT_PKG_CFLAGS = 
HAVE_DOT = 
INSURE = 
LD = 
LDFLAGS =  -L/tmp/blau/install-default/gt4.0.1-r3b-all-source-installer/lib
LIBS = 
LIBTOOL = $(SHELL) $(GLOBUS_LOCATION)/sbin/libtool-$(GLOBUS_FLAVOR_NAME)
LN_S = 
MAINT = #
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = 
PACKAGE = globus_gram_job_manager_setup_cobalt
PERL = 
RANLIB = 
COBALT_SETUP_FLAGS = @COBALT_SETUP_FLAGS@
VERSION = 1.1
builddir = /home/copej/downloads/sge/globus_gram_job_manager_setup_cobalt-1.1
cross_compiling = 
lac_doxygen_examples = 
lac_doxygen_file_patterns = 
lac_doxygen_installdox = 
lac_doxygen_internal_tagfiles = 
lac_doxygen_output_tagfile = 
lac_doxygen_predefines = 
lac_doxygen_project = 
lac_doxygen_srcdirs = 
lac_doxygen_tagfiles = 

setupdir = $(GLOBUS_LOCATION)/setup/globus

testdir = $(GLOBUS_LOCATION)/test/$(PACKAGE)

scriptsysconfdir = $(GLOBUS_LOCATION)/etc

flavorincludedir = $(GLOBUS_LOCATION)/include/$(GLOBUS_FLAVOR_NAME)

pkgdir = $(GLOBUS_LOCATION)/etc/globus_packages/$(PACKAGE)

aclocaldir = $(GLOBUS_LOCATION)/share/globus_aclocal

amdirdir = $(GLOBUS_LOCATION)/share/globus_amdir

doxygendir = $(GLOBUS_LOCATION)/share/doxygen

docdir = $(GLOBUS_LOCATION)/share/doc

LINK_BAK = orig
AUTOMAKE_OPTIONS = no-dependencies

#
# Automake rules for installing and building doxygen docs
#

doxygen_installdox = 
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =  Doxyfile Doxyfile-internal
DIST_COMMON =  Doxyfile-internal.in Doxyfile.in Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(top_srcdir)/globus_automake_pre $(top_srcdir)/globus_automake_post
	cd $(top_srcdir) && $(AUTOMAKE) --foreign doxygen/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

Doxyfile: $(top_builddir)/config.status Doxyfile.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
Doxyfile-internal: $(top_builddir)/config.status Doxyfile-internal.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = doxygen

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile all-local
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-local install-data-am install-data install-am install \
uninstall-am uninstall all-local all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean

all-local: Doxyfile
	@if test ! -z ""; then \
		  Doxyfile;  \
		if test -n "$(doxygen_installdox)"; then \
		    if test -x ./doc/html/installdox; then \
		        $(PERL) ./doc/html/installdox $(doxygen_installdox) ./doc/html/*;\
		    fi ; \
		fi ; \
	fi

install-data-local:
	@if test ! -z ""; then                     \
		for dir in `find ./doc/* -type d -print|sed "s,./doc/,,"`; do \
			if test -z "`echo $${dir}|sed -n '/^man/ p'`"; then \
				$(INSTALL) -d -m 755 \
					$(DESTDIR)$(docdir)/globus_gram_job_manager_setup_cobalt/$${dir}; \
			else \
				$(INSTALL) -d -m 755 \
					$(DESTDIR)$(prefix)/$${dir}; \
			fi \
		done; \
		for file in `find ./doc -type f -print|sed "s,./doc/,,"`; do \
			if test -z "`echo $${file}|sed -n '/^man/ p'`"; then \
				$(INSTALL) -m 644 ./doc/$${file} \
					$(DESTDIR)$(docdir)/globus_gram_job_manager_setup_cobalt/$${file}; \
			else \
				$(INSTALL) -m 644 ./doc/$${file} \
					$(DESTDIR)$(prefix)/$${file};\
			fi \
		done \
	fi

clean-data-local:
	@if test ! -z ""; then \
		rm -rf ./doc*;          \
	fi

filelist:
	@if test ! -z ""; then \
		find ./doc -type f -print| \
		sed "s,./doc/man,$(prefix)/man,"| \
		sed "s,./doc,$(docdir)/globus_gram_job_manager_setup_cobalt," \
		>> $(FILELIST_FILE); \
	fi

dist-hook: all-local
	@if test ! -z ""; then \
		if test -d doc; then \
		    cp -r doc $(distdir)/doc ; \
		fi ; \
		if test -d doc-internal; then \
		    cp -r doc-internal $(distdir)/doc-internal ; \
		fi ; \
	fi ;

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
