#!/usr/bin/env python

__revision__ = '$Revision$'

import bridge, sys

def matchFilters(filters, path):
    if not filters:
        return True
    for f in filters:
        f_flds = f.split(':')
        p_flds = path.split(':')
        fchk = [i for i in range(len(f_flds)) if f_flds[i] != '*']
        if False not in \
           [f_flds[i] == p_flds[i] for i in fchk]:
            return True
    return False

if __name__ == '__main__':
    if len(sys.argv) > 1:
        filters = sys.argv[1:]
    else:
        filters = []

    parts = bridge.PartList()
    for part in parts:
        for key in part.Visible():
            fullkey = "partition:%s:%s" % (part.id, key)
            if matchFilters(filters, fullkey):
                print "%s = %s" % (fullkey, getattr(part, key))
    jobs = bridge.JobList()
    for job in jobs:
        for key in job.Visible():
            fullkey = "job:%s:%s" % (job.id, key)
            if matchFilters(filters, fullkey):
                print "%s = %s" % (fullkey, getattr(job, key))


